### ISSUE TITLE
Don't know whats up...

### ISSUE THREAD

**Issue by boydcase31** [Keyaku/OpenJailbreak#1]
When I run:
./autobrew.sh

everything goes fine until it starts to fetch the OpenJailbreak libs. 
Here is my terminal output:

Boyds-MacBook-Air:OpenJailbreak boydcase$ ./autobrew.sh
OpenJailbreak library build script - DarkMalloc 2013
Homebrew (kegs) version - Keyaku 2015

Checking if required packages are installed...
All required packages are installed!

Fetching libcrippy-1...
Cloning into 'libcrippy'...
fatal: remote error: access denied or repository not exported: /libcrippy.git

Fetching libdyldcache-1...
Cloning into 'libdyldcache'...
fatal: remote error: access denied or repository not exported: /libdyldcache.git

Fetching libmacho-1...
Cloning into 'libmacho'...
fatal: remote error: access denied or repository not exported: /libmacho.git

Fetching libmbdb-1...
Cloning into 'libmbdb'...
fatal: remote error: access denied or repository not exported: /libmbdb.git

Fetching libimobiledevice-1...
Cloning into 'libimobiledevice'...
fatal: remote error: access denied or repository not exported: /libimobiledevice.git

Fetching libcnary-1...
Cloning into 'libcnary'...
fatal: remote error: access denied or repository not exported: /libcnary.git

Fetching libidevicebackup-1-0...
Cloning into 'libidevicebackup'...
fatal: remote error: access denied or repository not exported: /libidevicebackup.git

Fetching libidevicecrashreport-1...
Cloning into 'libidevicecrashreport'...
fatal: remote error: access denied or repository not exported: /libidevicecrashreport.git

Fetching idevicerestore-1...
Cloning into 'idevicerestore'...
fatal: remote error: access denied or repository not exported: /idevicerestore.git

Fetching libimg3-1...
Cloning into 'libimg3'...
fatal: remote error: access denied or repository not exported: /libimg3.git

Fetching libimg4-1...
Cloning into 'libimg4'...
fatal: remote error: access denied or repository not exported: /libimg4.git

Fetching libipsw-1...
Cloning into 'libipsw'...
fatal: remote error: access denied or repository not exported: /libipsw.git

Fetching libtss-1...
Cloning into 'libtss'...
fatal: remote error: access denied or repository not exported: /libtss.git

Fetching libpois0n-1...
Cloning into 'libpois0n'...
fatal: remote error: access denied or repository not exported: /libpois0n.git

Fetching libhfsplus-1...
Cloning into 'libhfsplus'...
fatal: remote error: access denied or repository not exported: /libhfsplus.git

Fetching libdmg-1...
Cloning into 'libdmg'...
fatal: remote error: access denied or repository not exported: /libdmg.git

Fetching libirecovery-2...
Cloning into 'libirecovery'...
fatal: remote error: access denied or repository not exported: /libirecovery.git

Fetching libpartialzip-1...
Cloning into 'libpartialzip'...
fatal: remote error: access denied or repository not exported: /libpartialzip.git

Fetching libsyringe-1...
Cloning into 'libsyringe'...
fatal: remote error: access denied or repository not exported: /libsyringe.git

Warning: Problems occurred while...
- Fetching libcrippy-1
- Fetching libdyldcache-1
- Fetching libmacho-1
- Fetching libmbdb-1
- Fetching libimobiledevice-1
- Fetching libcnary-1
- Fetching libidevicebackup-1-0
- Fetching libidevicecrashreport-1
- Fetching idevicerestore-1
- Fetching libimg3-1
- Fetching libimg4-1
- Fetching libipsw-1
- Fetching libtss-1
- Fetching libpois0n-1
- Fetching libhfsplus-1
- Fetching libdmg-1
- Fetching libirecovery-2
- Fetching libpartialzip-1
- Fetching libsyringe-1

Check what went wrong. If necessary, file an issue in my Github project page (CMD+Double Click the following link):
    https://github.com/Keyaku/OpenJailbreak

Boyds-MacBook-Air:OpenJailbreak boydcase$

**Comment by Keyaku** [comment]
~~The sources at OpenJailbreak.org now have a slightly different name. I fixed this quickly but then found out another problem that I must sort out in a bit.~~
First problem is fixed! Tell me what other issues arose before I close this.

**Comment by Keyaku** [comment]
No more issues reported related to this one.
